version: '3.8'

services:

  backend:
    build:
      context: .
      args:
        - REMOTE_GIT_LINK_BACKEND=${REMOTE_GIT_LINK_BACKEND}
        - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
        - ASPNETCORE_URLS=http://+:80
        - ASPNETCORE_Kestrel__Certificates__Default__Password=${SSL_CERTIFICATE_PASS}
        - ConnectionStrings__DefaultConnection=Host=${POSTGRES_SERVER};Port=${POSTGRES_PORT};Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      dockerfile: docker/Backend.Dockerfile
    container_name: backend
    environment:
      - REMOTE_GIT_LINK_BACKEND=${REMOTE_GIT_LINK_BACKEND}
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${SSL_CERTIFICATE_PASS}
      - ConnectionStrings__DefaultConnection=Host=${POSTGRES_SERVER};Port=${POSTGRES_PORT};Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
    ports:
      - "${HTTP_PORT_SERVER}:80"
      - "${HTTPS_PORT_SERVER}:443"
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    networks:
      - network2

  client-build:
    build:
      context: .
      dockerfile: docker/Client.Dockerfile
    container_name: client
    depends_on:
      backend:
        condition: service_started
    volumes:
      - ./builds:/builds
      - ./sources/Backend/wwwroot/download:/output
    command: ["bash", "-c", "cp -r /build/* /output"]
    
  db:
    image: postgres:18
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./postgres_data:/var/lib/postgresql
    ports:
      - "${POSTGRES_PORT}:5432"
    restart: unless-stopped
    networks:
      - network2
        
networks:
  network2:
    name: "network2"