version: '3.8'

services:

  backend:
    build:
      context: .
      args:
        - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
        - ASPNETCORE_URLS=http://+:80
        - ASPNETCORE_Kestrel__Certificates__Default__Password=${SSL_CERTIFICATE_PASS}
        - ConnectionStrings__DefaultConnection=Host=${POSTGRES_SERVER};Port=${POSTGRES_PORT};Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      dockerfile: docker/Backend.Dockerfile
    container_name: backend
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${SSL_CERTIFICATE_PASS}
      - ConnectionStrings__DefaultConnection=Host=${POSTGRES_SERVER};Port=${POSTGRES_PORT};Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
    ports:
      - "${HTTP_PORT_SERVER}:80"
      - "${HTTPS_PORT_SERVER}:443"
      - "3478:3478/udp"
    restart: unless-stopped
    volumes:
      - downloads:/app/wwwroot/download
    depends_on:
      db:
        condition: service_healthy
    networks:
      - network2

#  client-build:
#    build:
#      context: .
#      dockerfile: docker/App.DockerFile
#    container_name: client
#    depends_on:
#      backend:
#        condition: service_started
#    volumes:
#      - ./downloads:/output
#    command: ["bash", "-c", "cp -r /build/* /output"]
    
  db:
    image: postgres:18
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./postgres_data:/var/lib/postgresql
    ports:
      - "${POSTGRES_PORT}:5432"
    restart: unless-stopped
    networks:
      - network2
  
  postgres_exporter:
    image: prometheuscommunity/postgres-exporter
    container_name: postgres_exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - network2
    restart: unless-stopped

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    depends_on:
      - postgres_exporter
    networks:
      - network2
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    container_name: grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_USERS_ALLOW_SIGN_UP: "false"
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - network2
    restart: unless-stopped
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 80
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "8081:80"
    networks:
      - network2
    restart: unless-stopped

networks:
  network2:
    name: "network2"
    
volumes:
  downloads: